// Generated by Bisonc++ V6.08.00 on Mon, 03 Nov 2025 03:09:20 +0100

// base/comment

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved_::UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN_ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok_
// which is applied. In this errTok_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved_
    {
        UNDETERMINED_   = -2,
        EOF_            = -1,
        errTok_         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    inline bool operator&(StateType lhs, StateType rhs)
    {
        return (static_cast<int>(lhs) & rhs) != 0;
    }
    enum StateTransition
    {
        ACCEPT_   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI_     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR_     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION_ = 10
    };

// Productions Info Records:
PI_ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {302, 6}, // 1: program (T_PROGRAM) ->  T_PROGRAM T_ID declarations T_BEGIN statements T_END
     {305, 1}, // 2: type_sequence ->  type
     {305, 3}, // 3: type_sequence (T_COMMA) ->  type_sequence T_COMMA type
     {303, 0}, // 4: declarations ->  <empty>
     {303, 2}, // 5: declarations ->  declaration declarations
     {307, 3}, // 6: declaration (T_SEMICOLON) ->  type variable_sequence T_SEMICOLON
     {307, 4}, // 7: declaration (T_LIST) ->  type T_LIST T_ID T_SEMICOLON
     {307, 5}, // 8: declaration (T_LESS) ->  T_LESS type_sequence T_GR T_ID T_SEMICOLON
     {306, 1}, // 9: type (T_INTEGER) ->  T_INTEGER
     {306, 1}, // 10: type (T_BOOLEAN) ->  T_BOOLEAN
     {308, 1}, // 11: variable_sequence (T_ID) ->  T_ID
     {308, 3}, // 12: variable_sequence (T_COMMA) ->  variable_sequence T_COMMA T_ID
     {304, 1}, // 13: statements ->  statement
     {304, 2}, // 14: statements ->  statement statements
     {309, 2}, // 15: statement (T_SKIP) ->  T_SKIP T_SEMICOLON
     {309, 1}, // 16: statement ->  assignment
     {309, 1}, // 17: statement ->  read
     {309, 1}, // 18: statement ->  write
     {309, 1}, // 19: statement ->  branch
     {309, 1}, // 20: statement ->  loop
     {309, 6}, // 21: statement (T_OPEN_SQ) ->  T_OPEN_SQ statement_no_semi T_PARALLEL statement_no_semi T_CLOSE_SQ T_SEMICOLON
     {315, 1}, // 22: statement_no_semi ->  assignment_no_semi
     {315, 1}, // 23: statement_no_semi ->  read_no_semi
     {315, 1}, // 24: statement_no_semi ->  write_no_semi
     {319, 1}, // 25: list_sequence ->  expression
     {319, 3}, // 26: list_sequence (T_COMMA) ->  list_sequence T_COMMA expression
     {310, 4}, // 27: assignment (T_ID) ->  T_ID T_ASSIGN expression T_SEMICOLON
     {310, 4}, // 28: assignment (T_ID) ->  T_ID T_APPENDMENT expression T_SEMICOLON
     {310, 7}, // 29: assignment (T_ID) ->  T_ID T_OPEN_SQ T_NUM T_CLOSE_SQ T_ASSIGN expression T_SEMICOLON
     {310, 6}, // 30: assignment (T_ID) ->  T_ID T_DOT T_NUM T_ASSIGN expression T_SEMICOLON
     {316, 3}, // 31: assignment_no_semi (T_ID) ->  T_ID T_ASSIGN expression
     {311, 5}, // 32: read (T_READ) ->  T_READ T_OPEN T_ID T_CLOSE T_SEMICOLON
     {311, 7}, // 33: read (T_READ) ->  T_READ T_OPEN T_ID T_DOT T_NUM T_CLOSE T_SEMICOLON
     {317, 4}, // 34: read_no_semi (T_READ) ->  T_READ T_OPEN T_ID T_CLOSE
     {312, 5}, // 35: write (T_WRITE) ->  T_WRITE T_OPEN expression T_CLOSE T_SEMICOLON
     {318, 4}, // 36: write_no_semi (T_WRITE) ->  T_WRITE T_OPEN expression T_CLOSE
     {313, 5}, // 37: branch (T_IF) ->  T_IF expression T_THEN statements T_ENDIF
     {313, 7}, // 38: branch (T_IF) ->  T_IF expression T_THEN statements T_ELSE statements T_ENDIF
     {314, 5}, // 39: loop (T_WHILE) ->  T_WHILE expression T_DO statements T_DONE
     {321, 2}, // 40: list (T_OPEN_SQ) ->  T_OPEN_SQ T_CLOSE_SQ
     {321, 3}, // 41: list (T_OPEN_SQ) ->  T_OPEN_SQ list_sequence T_CLOSE_SQ
     {320, 1}, // 42: expression (T_NUM) ->  T_NUM
     {320, 1}, // 43: expression (T_TRUE) ->  T_TRUE
     {320, 1}, // 44: expression (T_FALSE) ->  T_FALSE
     {320, 1}, // 45: expression (T_ID) ->  T_ID
     {320, 3}, // 46: expression (T_ADD) ->  expression T_ADD expression
     {320, 3}, // 47: expression (T_SUB) ->  expression T_SUB expression
     {320, 3}, // 48: expression (T_MUL) ->  expression T_MUL expression
     {320, 3}, // 49: expression (T_DIV) ->  expression T_DIV expression
     {320, 3}, // 50: expression (T_MOD) ->  expression T_MOD expression
     {320, 3}, // 51: expression (T_LESS) ->  expression T_LESS expression
     {320, 3}, // 52: expression (T_GR) ->  expression T_GR expression
     {320, 3}, // 53: expression (T_EQ) ->  expression T_EQ expression
     {320, 3}, // 54: expression (T_AND) ->  expression T_AND expression
     {320, 3}, // 55: expression (T_OR) ->  expression T_OR expression
     {320, 2}, // 56: expression (T_NOT) ->  T_NOT expression
     {320, 3}, // 57: expression (T_OPEN) ->  T_OPEN expression T_CLOSE
     {320, 3}, // 58: expression (T_SHIFT) ->  expression T_SHIFT expression
     {320, 7}, // 59: expression (T_OPEN) ->  T_OPEN expression T_QUESTION expression T_COLON expression T_CLOSE
     {320, 4}, // 60: expression (T_ID) ->  T_ID T_OPEN_SQ T_NUM T_CLOSE_SQ
     {320, 1}, // 61: expression ->  list
     {320, 3}, // 62: expression (T_PLUS_PLUS) ->  expression T_PLUS_PLUS expression
     {320, 3}, // 63: expression (T_ID) ->  T_ID T_DOT T_NUM
     {322, 1}, // 64: program_$ ->  program
};

// State info and SR_ transitions for each state.


SR_ s_0[] =
{
    { { REQ_TOKEN}, { 3} },             
    { {       302}, { 1} }, // program  
    { {       257}, { 2} }, // T_PROGRAM
    { {         0}, { 0} },             
};

SR_ s_1[] =
{
    { { REQ_TOKEN}, {       2} }, 
    { {      EOF_}, { ACCEPT_} }, 
    { {         0}, {       0} }, 
};

SR_ s_2[] =
{
    { { REQ_TOKEN}, { 2} },        
    { {       287}, { 3} }, // T_ID
    { {         0}, { 0} },        
};

SR_ s_3[] =
{
    { { REQ_DEF}, {  7} },                
    { {     303}, {  4} }, // declarations
    { {     307}, {  5} }, // declaration 
    { {     306}, {  6} }, // type        
    { {     292}, {  7} }, // T_LESS      
    { {     260}, {  8} }, // T_INTEGER   
    { {     261}, {  9} }, // T_BOOLEAN   
    { {       0}, { -4} },                
};

SR_ s_4[] =
{
    { { REQ_TOKEN}, {  2} },           
    { {       258}, { 10} }, // T_BEGIN
    { {         0}, {  0} },           
};

SR_ s_5[] =
{
    { { REQ_DEF}, {  7} },                
    { {     303}, { 11} }, // declarations
    { {     307}, {  5} }, // declaration 
    { {     306}, {  6} }, // type        
    { {     292}, {  7} }, // T_LESS      
    { {     260}, {  8} }, // T_INTEGER   
    { {     261}, {  9} }, // T_BOOLEAN   
    { {       0}, { -4} },                
};

SR_ s_6[] =
{
    { { REQ_TOKEN}, {  4} },                     
    { {       308}, { 12} }, // variable_sequence
    { {       280}, { 13} }, // T_LIST           
    { {       287}, { 14} }, // T_ID             
    { {         0}, {  0} },                     
};

SR_ s_7[] =
{
    { { REQ_TOKEN}, {  5} },                 
    { {       305}, { 15} }, // type_sequence
    { {       306}, { 16} }, // type         
    { {       260}, {  8} }, // T_INTEGER    
    { {       261}, {  9} }, // T_BOOLEAN    
    { {         0}, {  0} },                 
};

SR_ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR_ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR_ s_10[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       304}, { 17} }, // statements
    { {       309}, { 18} }, // statement 
    { {       263}, { 19} }, // T_SKIP    
    { {       310}, { 20} }, // assignment
    { {       311}, { 21} }, // read      
    { {       312}, { 22} }, // write     
    { {       313}, { 23} }, // branch    
    { {       314}, { 24} }, // loop      
    { {       277}, { 25} }, // T_OPEN_SQ 
    { {       287}, { 26} }, // T_ID      
    { {       271}, { 27} }, // T_READ    
    { {       272}, { 28} }, // T_WRITE   
    { {       264}, { 29} }, // T_IF      
    { {       268}, { 30} }, // T_WHILE   
    { {         0}, {  0} },              
};

SR_ s_11[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR_ s_12[] =
{
    { { REQ_TOKEN}, {  3} },               
    { {       262}, { 31} }, // T_SEMICOLON
    { {       279}, { 32} }, // T_COMMA    
    { {         0}, {  0} },               
};

SR_ s_13[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       287}, { 33} }, // T_ID
    { {         0}, {  0} },        
};

SR_ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR_ s_15[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       293}, { 34} }, // T_GR   
    { {       279}, { 35} }, // T_COMMA
    { {         0}, {  0} },           
};

SR_ s_16[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR_ s_17[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       259}, { 36} }, // T_END
    { {         0}, {  0} },         
};

SR_ s_18[] =
{
    { { REQ_DEF}, {  15} },              
    { {     304}, {  37} }, // statements
    { {     309}, {  18} }, // statement 
    { {     263}, {  19} }, // T_SKIP    
    { {     310}, {  20} }, // assignment
    { {     311}, {  21} }, // read      
    { {     312}, {  22} }, // write     
    { {     313}, {  23} }, // branch    
    { {     314}, {  24} }, // loop      
    { {     277}, {  25} }, // T_OPEN_SQ 
    { {     287}, {  26} }, // T_ID      
    { {     271}, {  27} }, // T_READ    
    { {     272}, {  28} }, // T_WRITE   
    { {     264}, {  29} }, // T_IF      
    { {     268}, {  30} }, // T_WHILE   
    { {       0}, { -13} },              
};

SR_ s_19[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       262}, { 38} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR_ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR_ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR_ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR_ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR_ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR_ s_25[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       315}, { 39} }, // statement_no_semi 
    { {       316}, { 40} }, // assignment_no_semi
    { {       317}, { 41} }, // read_no_semi      
    { {       318}, { 42} }, // write_no_semi     
    { {       287}, { 43} }, // T_ID              
    { {       271}, { 44} }, // T_READ            
    { {       272}, { 45} }, // T_WRITE           
    { {         0}, {  0} },                      
};

SR_ s_26[] =
{
    { { REQ_TOKEN}, {  5} },                
    { {       273}, { 46} }, // T_ASSIGN    
    { {       281}, { 47} }, // T_APPENDMENT
    { {       277}, { 48} }, // T_OPEN_SQ   
    { {       301}, { 49} }, // T_DOT       
    { {         0}, {  0} },                
};

SR_ s_27[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       282}, { 50} }, // T_OPEN
    { {         0}, {  0} },          
};

SR_ s_28[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       282}, { 51} }, // T_OPEN
    { {         0}, {  0} },          
};

SR_ s_29[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       320}, { 52} }, // expression
    { {       286}, { 53} }, // T_NUM     
    { {       284}, { 54} }, // T_TRUE    
    { {       285}, { 55} }, // T_FALSE   
    { {       287}, { 56} }, // T_ID      
    { {       300}, { 57} }, // T_NOT     
    { {       282}, { 58} }, // T_OPEN    
    { {       321}, { 59} }, // list      
    { {       277}, { 60} }, // T_OPEN_SQ 
    { {         0}, {  0} },              
};

SR_ s_30[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       320}, { 61} }, // expression
    { {       286}, { 53} }, // T_NUM     
    { {       284}, { 54} }, // T_TRUE    
    { {       285}, { 55} }, // T_FALSE   
    { {       287}, { 56} }, // T_ID      
    { {       300}, { 57} }, // T_NOT     
    { {       282}, { 58} }, // T_OPEN    
    { {       321}, { 59} }, // list      
    { {       277}, { 60} }, // T_OPEN_SQ 
    { {         0}, {  0} },              
};

SR_ s_31[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR_ s_32[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       287}, { 62} }, // T_ID
    { {         0}, {  0} },        
};

SR_ s_33[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       262}, { 63} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR_ s_34[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       287}, { 64} }, // T_ID
    { {         0}, {  0} },        
};

SR_ s_35[] =
{
    { { REQ_TOKEN}, {  4} },             
    { {       306}, { 65} }, // type     
    { {       260}, {  8} }, // T_INTEGER
    { {       261}, {  9} }, // T_BOOLEAN
    { {         0}, {  0} },             
};

SR_ s_36[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR_ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR_ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR_ s_39[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       276}, { 66} }, // T_PARALLEL
    { {         0}, {  0} },              
};

SR_ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR_ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR_ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR_ s_43[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       273}, { 67} }, // T_ASSIGN
    { {         0}, {  0} },            
};

SR_ s_44[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       282}, { 68} }, // T_OPEN
    { {         0}, {  0} },          
};

SR_ s_45[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       282}, { 69} }, // T_OPEN
    { {         0}, {  0} },          
};

SR_ s_46[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       320}, { 70} }, // expression
    { {       286}, { 53} }, // T_NUM     
    { {       284}, { 54} }, // T_TRUE    
    { {       285}, { 55} }, // T_FALSE   
    { {       287}, { 56} }, // T_ID      
    { {       300}, { 57} }, // T_NOT     
    { {       282}, { 58} }, // T_OPEN    
    { {       321}, { 59} }, // list      
    { {       277}, { 60} }, // T_OPEN_SQ 
    { {         0}, {  0} },              
};

SR_ s_47[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       320}, { 71} }, // expression
    { {       286}, { 53} }, // T_NUM     
    { {       284}, { 54} }, // T_TRUE    
    { {       285}, { 55} }, // T_FALSE   
    { {       287}, { 56} }, // T_ID      
    { {       300}, { 57} }, // T_NOT     
    { {       282}, { 58} }, // T_OPEN    
    { {       321}, { 59} }, // list      
    { {       277}, { 60} }, // T_OPEN_SQ 
    { {         0}, {  0} },              
};

SR_ s_48[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       286}, { 72} }, // T_NUM
    { {         0}, {  0} },         
};

SR_ s_49[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       286}, { 73} }, // T_NUM
    { {         0}, {  0} },         
};

SR_ s_50[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       287}, { 74} }, // T_ID
    { {         0}, {  0} },        
};

SR_ s_51[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       320}, { 75} }, // expression
    { {       286}, { 53} }, // T_NUM     
    { {       284}, { 54} }, // T_TRUE    
    { {       285}, { 55} }, // T_FALSE   
    { {       287}, { 56} }, // T_ID      
    { {       300}, { 57} }, // T_NOT     
    { {       282}, { 58} }, // T_OPEN    
    { {       321}, { 59} }, // list      
    { {       277}, { 60} }, // T_OPEN_SQ 
    { {         0}, {  0} },              
};

SR_ s_52[] =
{
    { { REQ_TOKEN}, { 14} },               
    { {       265}, { 76} }, // T_THEN     
    { {       294}, { 77} }, // T_ADD      
    { {       295}, { 78} }, // T_SUB      
    { {       296}, { 79} }, // T_MUL      
    { {       297}, { 80} }, // T_DIV      
    { {       298}, { 81} }, // T_MOD      
    { {       292}, { 82} }, // T_LESS     
    { {       293}, { 83} }, // T_GR       
    { {       291}, { 84} }, // T_EQ       
    { {       290}, { 85} }, // T_AND      
    { {       289}, { 86} }, // T_OR       
    { {       288}, { 87} }, // T_SHIFT    
    { {       299}, { 88} }, // T_PLUS_PLUS
    { {         0}, {  0} },               
};

SR_ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR_ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR_ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR_ s_56[] =
{
    { { REQ_DEF}, {   3} },             
    { {     277}, {  89} }, // T_OPEN_SQ
    { {     301}, {  90} }, // T_DOT    
    { {       0}, { -45} },             
};

SR_ s_57[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       320}, { 91} }, // expression
    { {       286}, { 53} }, // T_NUM     
    { {       284}, { 54} }, // T_TRUE    
    { {       285}, { 55} }, // T_FALSE   
    { {       287}, { 56} }, // T_ID      
    { {       300}, { 57} }, // T_NOT     
    { {       282}, { 58} }, // T_OPEN    
    { {       321}, { 59} }, // list      
    { {       277}, { 60} }, // T_OPEN_SQ 
    { {         0}, {  0} },              
};

SR_ s_58[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       320}, { 92} }, // expression
    { {       286}, { 53} }, // T_NUM     
    { {       284}, { 54} }, // T_TRUE    
    { {       285}, { 55} }, // T_FALSE   
    { {       287}, { 56} }, // T_ID      
    { {       300}, { 57} }, // T_NOT     
    { {       282}, { 58} }, // T_OPEN    
    { {       321}, { 59} }, // list      
    { {       277}, { 60} }, // T_OPEN_SQ 
    { {         0}, {  0} },              
};

SR_ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR_ s_60[] =
{
    { { REQ_TOKEN}, { 12} },                 
    { {       278}, { 93} }, // T_CLOSE_SQ   
    { {       319}, { 94} }, // list_sequence
    { {       320}, { 95} }, // expression   
    { {       286}, { 53} }, // T_NUM        
    { {       284}, { 54} }, // T_TRUE       
    { {       285}, { 55} }, // T_FALSE      
    { {       287}, { 56} }, // T_ID         
    { {       300}, { 57} }, // T_NOT        
    { {       282}, { 58} }, // T_OPEN       
    { {       321}, { 59} }, // list         
    { {       277}, { 60} }, // T_OPEN_SQ    
    { {         0}, {  0} },                 
};

SR_ s_61[] =
{
    { { REQ_TOKEN}, { 14} },               
    { {       269}, { 96} }, // T_DO       
    { {       294}, { 77} }, // T_ADD      
    { {       295}, { 78} }, // T_SUB      
    { {       296}, { 79} }, // T_MUL      
    { {       297}, { 80} }, // T_DIV      
    { {       298}, { 81} }, // T_MOD      
    { {       292}, { 82} }, // T_LESS     
    { {       293}, { 83} }, // T_GR       
    { {       291}, { 84} }, // T_EQ       
    { {       290}, { 85} }, // T_AND      
    { {       289}, { 86} }, // T_OR       
    { {       288}, { 87} }, // T_SHIFT    
    { {       299}, { 88} }, // T_PLUS_PLUS
    { {         0}, {  0} },               
};

SR_ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR_ s_63[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR_ s_64[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       262}, { 97} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR_ s_65[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR_ s_66[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       315}, { 98} }, // statement_no_semi 
    { {       316}, { 40} }, // assignment_no_semi
    { {       317}, { 41} }, // read_no_semi      
    { {       318}, { 42} }, // write_no_semi     
    { {       287}, { 43} }, // T_ID              
    { {       271}, { 44} }, // T_READ            
    { {       272}, { 45} }, // T_WRITE           
    { {         0}, {  0} },                      
};

SR_ s_67[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       320}, { 99} }, // expression
    { {       286}, { 53} }, // T_NUM     
    { {       284}, { 54} }, // T_TRUE    
    { {       285}, { 55} }, // T_FALSE   
    { {       287}, { 56} }, // T_ID      
    { {       300}, { 57} }, // T_NOT     
    { {       282}, { 58} }, // T_OPEN    
    { {       321}, { 59} }, // list      
    { {       277}, { 60} }, // T_OPEN_SQ 
    { {         0}, {  0} },              
};

SR_ s_68[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       287}, { 100} }, // T_ID
    { {         0}, {   0} },        
};

SR_ s_69[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 101} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_70[] =
{
    { { REQ_TOKEN}, {  14} },               
    { {       262}, { 102} }, // T_SEMICOLON
    { {       294}, {  77} }, // T_ADD      
    { {       295}, {  78} }, // T_SUB      
    { {       296}, {  79} }, // T_MUL      
    { {       297}, {  80} }, // T_DIV      
    { {       298}, {  81} }, // T_MOD      
    { {       292}, {  82} }, // T_LESS     
    { {       293}, {  83} }, // T_GR       
    { {       291}, {  84} }, // T_EQ       
    { {       290}, {  85} }, // T_AND      
    { {       289}, {  86} }, // T_OR       
    { {       288}, {  87} }, // T_SHIFT    
    { {       299}, {  88} }, // T_PLUS_PLUS
    { {         0}, {   0} },               
};

SR_ s_71[] =
{
    { { REQ_TOKEN}, {  14} },               
    { {       262}, { 103} }, // T_SEMICOLON
    { {       294}, {  77} }, // T_ADD      
    { {       295}, {  78} }, // T_SUB      
    { {       296}, {  79} }, // T_MUL      
    { {       297}, {  80} }, // T_DIV      
    { {       298}, {  81} }, // T_MOD      
    { {       292}, {  82} }, // T_LESS     
    { {       293}, {  83} }, // T_GR       
    { {       291}, {  84} }, // T_EQ       
    { {       290}, {  85} }, // T_AND      
    { {       289}, {  86} }, // T_OR       
    { {       288}, {  87} }, // T_SHIFT    
    { {       299}, {  88} }, // T_PLUS_PLUS
    { {         0}, {   0} },               
};

SR_ s_72[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       278}, { 104} }, // T_CLOSE_SQ
    { {         0}, {   0} },              
};

SR_ s_73[] =
{
    { { REQ_TOKEN}, {   2} },            
    { {       273}, { 105} }, // T_ASSIGN
    { {         0}, {   0} },            
};

SR_ s_74[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       283}, { 106} }, // T_CLOSE
    { {       301}, { 107} }, // T_DOT  
    { {         0}, {   0} },           
};

SR_ s_75[] =
{
    { { REQ_TOKEN}, {  14} },               
    { {       283}, { 108} }, // T_CLOSE    
    { {       294}, {  77} }, // T_ADD      
    { {       295}, {  78} }, // T_SUB      
    { {       296}, {  79} }, // T_MUL      
    { {       297}, {  80} }, // T_DIV      
    { {       298}, {  81} }, // T_MOD      
    { {       292}, {  82} }, // T_LESS     
    { {       293}, {  83} }, // T_GR       
    { {       291}, {  84} }, // T_EQ       
    { {       290}, {  85} }, // T_AND      
    { {       289}, {  86} }, // T_OR       
    { {       288}, {  87} }, // T_SHIFT    
    { {       299}, {  88} }, // T_PLUS_PLUS
    { {         0}, {   0} },               
};

SR_ s_76[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       304}, { 109} }, // statements
    { {       309}, {  18} }, // statement 
    { {       263}, {  19} }, // T_SKIP    
    { {       310}, {  20} }, // assignment
    { {       311}, {  21} }, // read      
    { {       312}, {  22} }, // write     
    { {       313}, {  23} }, // branch    
    { {       314}, {  24} }, // loop      
    { {       277}, {  25} }, // T_OPEN_SQ 
    { {       287}, {  26} }, // T_ID      
    { {       271}, {  27} }, // T_READ    
    { {       272}, {  28} }, // T_WRITE   
    { {       264}, {  29} }, // T_IF      
    { {       268}, {  30} }, // T_WHILE   
    { {         0}, {   0} },              
};

SR_ s_77[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 110} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_78[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 111} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_79[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 112} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_80[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 113} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_81[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 114} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_82[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 115} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_83[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 116} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_84[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 117} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_85[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 118} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_86[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 119} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_87[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 120} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_88[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 121} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_89[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       286}, { 122} }, // T_NUM
    { {         0}, {   0} },         
};

SR_ s_90[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       286}, { 123} }, // T_NUM
    { {         0}, {   0} },         
};

SR_ s_91[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -56} }, 
};

SR_ s_92[] =
{
    { { REQ_TOKEN}, {  15} },               
    { {       283}, { 124} }, // T_CLOSE    
    { {       275}, { 125} }, // T_QUESTION 
    { {       294}, {  77} }, // T_ADD      
    { {       295}, {  78} }, // T_SUB      
    { {       296}, {  79} }, // T_MUL      
    { {       297}, {  80} }, // T_DIV      
    { {       298}, {  81} }, // T_MOD      
    { {       292}, {  82} }, // T_LESS     
    { {       293}, {  83} }, // T_GR       
    { {       291}, {  84} }, // T_EQ       
    { {       290}, {  85} }, // T_AND      
    { {       289}, {  86} }, // T_OR       
    { {       288}, {  87} }, // T_SHIFT    
    { {       299}, {  88} }, // T_PLUS_PLUS
    { {         0}, {   0} },               
};

SR_ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR_ s_94[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       278}, { 126} }, // T_CLOSE_SQ
    { {       279}, { 127} }, // T_COMMA   
    { {         0}, {   0} },              
};

SR_ s_95[] =
{
    { { REQ_DEF}, {  13} },               
    { {     294}, {  77} }, // T_ADD      
    { {     295}, {  78} }, // T_SUB      
    { {     296}, {  79} }, // T_MUL      
    { {     297}, {  80} }, // T_DIV      
    { {     298}, {  81} }, // T_MOD      
    { {     292}, {  82} }, // T_LESS     
    { {     293}, {  83} }, // T_GR       
    { {     291}, {  84} }, // T_EQ       
    { {     290}, {  85} }, // T_AND      
    { {     289}, {  86} }, // T_OR       
    { {     288}, {  87} }, // T_SHIFT    
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -25} },               
};

SR_ s_96[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       304}, { 128} }, // statements
    { {       309}, {  18} }, // statement 
    { {       263}, {  19} }, // T_SKIP    
    { {       310}, {  20} }, // assignment
    { {       311}, {  21} }, // read      
    { {       312}, {  22} }, // write     
    { {       313}, {  23} }, // branch    
    { {       314}, {  24} }, // loop      
    { {       277}, {  25} }, // T_OPEN_SQ 
    { {       287}, {  26} }, // T_ID      
    { {       271}, {  27} }, // T_READ    
    { {       272}, {  28} }, // T_WRITE   
    { {       264}, {  29} }, // T_IF      
    { {       268}, {  30} }, // T_WHILE   
    { {         0}, {   0} },              
};

SR_ s_97[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR_ s_98[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       278}, { 129} }, // T_CLOSE_SQ
    { {         0}, {   0} },              
};

SR_ s_99[] =
{
    { { REQ_DEF}, {  13} },               
    { {     294}, {  77} }, // T_ADD      
    { {     295}, {  78} }, // T_SUB      
    { {     296}, {  79} }, // T_MUL      
    { {     297}, {  80} }, // T_DIV      
    { {     298}, {  81} }, // T_MOD      
    { {     292}, {  82} }, // T_LESS     
    { {     293}, {  83} }, // T_GR       
    { {     291}, {  84} }, // T_EQ       
    { {     290}, {  85} }, // T_AND      
    { {     289}, {  86} }, // T_OR       
    { {     288}, {  87} }, // T_SHIFT    
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -31} },               
};

SR_ s_100[] =
{
    { { REQ_TOKEN}, {   2} },           
    { {       283}, { 130} }, // T_CLOSE
    { {         0}, {   0} },           
};

SR_ s_101[] =
{
    { { REQ_TOKEN}, {  14} },               
    { {       283}, { 131} }, // T_CLOSE    
    { {       294}, {  77} }, // T_ADD      
    { {       295}, {  78} }, // T_SUB      
    { {       296}, {  79} }, // T_MUL      
    { {       297}, {  80} }, // T_DIV      
    { {       298}, {  81} }, // T_MOD      
    { {       292}, {  82} }, // T_LESS     
    { {       293}, {  83} }, // T_GR       
    { {       291}, {  84} }, // T_EQ       
    { {       290}, {  85} }, // T_AND      
    { {       289}, {  86} }, // T_OR       
    { {       288}, {  87} }, // T_SHIFT    
    { {       299}, {  88} }, // T_PLUS_PLUS
    { {         0}, {   0} },               
};

SR_ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR_ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR_ s_104[] =
{
    { { REQ_TOKEN}, {   2} },            
    { {       273}, { 132} }, // T_ASSIGN
    { {         0}, {   0} },            
};

SR_ s_105[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 133} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_106[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       262}, { 134} }, // T_SEMICOLON
    { {         0}, {   0} },               
};

SR_ s_107[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       286}, { 135} }, // T_NUM
    { {         0}, {   0} },         
};

SR_ s_108[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       262}, { 136} }, // T_SEMICOLON
    { {         0}, {   0} },               
};

SR_ s_109[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       267}, { 137} }, // T_ENDIF
    { {       266}, { 138} }, // T_ELSE 
    { {         0}, {   0} },           
};

SR_ s_110[] =
{
    { { REQ_DEF}, {   5} },               
    { {     296}, {  79} }, // T_MUL      
    { {     297}, {  80} }, // T_DIV      
    { {     298}, {  81} }, // T_MOD      
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -46} },               
};

SR_ s_111[] =
{
    { { REQ_DEF}, {   5} },               
    { {     296}, {  79} }, // T_MUL      
    { {     297}, {  80} }, // T_DIV      
    { {     298}, {  81} }, // T_MOD      
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -47} },               
};

SR_ s_112[] =
{
    { { REQ_DEF}, {   2} },               
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -48} },               
};

SR_ s_113[] =
{
    { { REQ_DEF}, {   2} },               
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -49} },               
};

SR_ s_114[] =
{
    { { REQ_DEF}, {   2} },               
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -50} },               
};

SR_ s_115[] =
{
    { { REQ_DEF}, {   7} },               
    { {     294}, {  77} }, // T_ADD      
    { {     295}, {  78} }, // T_SUB      
    { {     296}, {  79} }, // T_MUL      
    { {     297}, {  80} }, // T_DIV      
    { {     298}, {  81} }, // T_MOD      
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -51} },               
};

SR_ s_116[] =
{
    { { REQ_DEF}, {   7} },               
    { {     294}, {  77} }, // T_ADD      
    { {     295}, {  78} }, // T_SUB      
    { {     296}, {  79} }, // T_MUL      
    { {     297}, {  80} }, // T_DIV      
    { {     298}, {  81} }, // T_MOD      
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -52} },               
};

SR_ s_117[] =
{
    { { REQ_DEF}, {   9} },               
    { {     294}, {  77} }, // T_ADD      
    { {     295}, {  78} }, // T_SUB      
    { {     296}, {  79} }, // T_MUL      
    { {     297}, {  80} }, // T_DIV      
    { {     298}, {  81} }, // T_MOD      
    { {     292}, {  82} }, // T_LESS     
    { {     293}, {  83} }, // T_GR       
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -53} },               
};

SR_ s_118[] =
{
    { { REQ_DEF}, {  10} },               
    { {     294}, {  77} }, // T_ADD      
    { {     295}, {  78} }, // T_SUB      
    { {     296}, {  79} }, // T_MUL      
    { {     297}, {  80} }, // T_DIV      
    { {     298}, {  81} }, // T_MOD      
    { {     292}, {  82} }, // T_LESS     
    { {     293}, {  83} }, // T_GR       
    { {     291}, {  84} }, // T_EQ       
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -54} },               
};

SR_ s_119[] =
{
    { { REQ_DEF}, {  10} },               
    { {     294}, {  77} }, // T_ADD      
    { {     295}, {  78} }, // T_SUB      
    { {     296}, {  79} }, // T_MUL      
    { {     297}, {  80} }, // T_DIV      
    { {     298}, {  81} }, // T_MOD      
    { {     292}, {  82} }, // T_LESS     
    { {     293}, {  83} }, // T_GR       
    { {     291}, {  84} }, // T_EQ       
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -55} },               
};

SR_ s_120[] =
{
    { { REQ_DEF}, {  12} },               
    { {     294}, {  77} }, // T_ADD      
    { {     295}, {  78} }, // T_SUB      
    { {     296}, {  79} }, // T_MUL      
    { {     297}, {  80} }, // T_DIV      
    { {     298}, {  81} }, // T_MOD      
    { {     292}, {  82} }, // T_LESS     
    { {     293}, {  83} }, // T_GR       
    { {     291}, {  84} }, // T_EQ       
    { {     290}, {  85} }, // T_AND      
    { {     289}, {  86} }, // T_OR       
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -58} },               
};

SR_ s_121[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -62} }, 
};

SR_ s_122[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       278}, { 139} }, // T_CLOSE_SQ
    { {         0}, {   0} },              
};

SR_ s_123[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR_ s_124[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR_ s_125[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 140} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_126[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR_ s_127[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 141} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_128[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       270}, { 142} }, // T_DONE
    { {         0}, {   0} },          
};

SR_ s_129[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       262}, { 143} }, // T_SEMICOLON
    { {         0}, {   0} },               
};

SR_ s_130[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR_ s_131[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR_ s_132[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 144} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_133[] =
{
    { { REQ_TOKEN}, {  14} },               
    { {       262}, { 145} }, // T_SEMICOLON
    { {       294}, {  77} }, // T_ADD      
    { {       295}, {  78} }, // T_SUB      
    { {       296}, {  79} }, // T_MUL      
    { {       297}, {  80} }, // T_DIV      
    { {       298}, {  81} }, // T_MOD      
    { {       292}, {  82} }, // T_LESS     
    { {       293}, {  83} }, // T_GR       
    { {       291}, {  84} }, // T_EQ       
    { {       290}, {  85} }, // T_AND      
    { {       289}, {  86} }, // T_OR       
    { {       288}, {  87} }, // T_SHIFT    
    { {       299}, {  88} }, // T_PLUS_PLUS
    { {         0}, {   0} },               
};

SR_ s_134[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR_ s_135[] =
{
    { { REQ_TOKEN}, {   2} },           
    { {       283}, { 146} }, // T_CLOSE
    { {         0}, {   0} },           
};

SR_ s_136[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR_ s_137[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR_ s_138[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       304}, { 147} }, // statements
    { {       309}, {  18} }, // statement 
    { {       263}, {  19} }, // T_SKIP    
    { {       310}, {  20} }, // assignment
    { {       311}, {  21} }, // read      
    { {       312}, {  22} }, // write     
    { {       313}, {  23} }, // branch    
    { {       314}, {  24} }, // loop      
    { {       277}, {  25} }, // T_OPEN_SQ 
    { {       287}, {  26} }, // T_ID      
    { {       271}, {  27} }, // T_READ    
    { {       272}, {  28} }, // T_WRITE   
    { {       264}, {  29} }, // T_IF      
    { {       268}, {  30} }, // T_WHILE   
    { {         0}, {   0} },              
};

SR_ s_139[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR_ s_140[] =
{
    { { REQ_TOKEN}, {  14} },               
    { {       274}, { 148} }, // T_COLON    
    { {       294}, {  77} }, // T_ADD      
    { {       295}, {  78} }, // T_SUB      
    { {       296}, {  79} }, // T_MUL      
    { {       297}, {  80} }, // T_DIV      
    { {       298}, {  81} }, // T_MOD      
    { {       292}, {  82} }, // T_LESS     
    { {       293}, {  83} }, // T_GR       
    { {       291}, {  84} }, // T_EQ       
    { {       290}, {  85} }, // T_AND      
    { {       289}, {  86} }, // T_OR       
    { {       288}, {  87} }, // T_SHIFT    
    { {       299}, {  88} }, // T_PLUS_PLUS
    { {         0}, {   0} },               
};

SR_ s_141[] =
{
    { { REQ_DEF}, {  13} },               
    { {     294}, {  77} }, // T_ADD      
    { {     295}, {  78} }, // T_SUB      
    { {     296}, {  79} }, // T_MUL      
    { {     297}, {  80} }, // T_DIV      
    { {     298}, {  81} }, // T_MOD      
    { {     292}, {  82} }, // T_LESS     
    { {     293}, {  83} }, // T_GR       
    { {     291}, {  84} }, // T_EQ       
    { {     290}, {  85} }, // T_AND      
    { {     289}, {  86} }, // T_OR       
    { {     288}, {  87} }, // T_SHIFT    
    { {     299}, {  88} }, // T_PLUS_PLUS
    { {       0}, { -26} },               
};

SR_ s_142[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR_ s_143[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR_ s_144[] =
{
    { { REQ_TOKEN}, {  14} },               
    { {       262}, { 149} }, // T_SEMICOLON
    { {       294}, {  77} }, // T_ADD      
    { {       295}, {  78} }, // T_SUB      
    { {       296}, {  79} }, // T_MUL      
    { {       297}, {  80} }, // T_DIV      
    { {       298}, {  81} }, // T_MOD      
    { {       292}, {  82} }, // T_LESS     
    { {       293}, {  83} }, // T_GR       
    { {       291}, {  84} }, // T_EQ       
    { {       290}, {  85} }, // T_AND      
    { {       289}, {  86} }, // T_OR       
    { {       288}, {  87} }, // T_SHIFT    
    { {       299}, {  88} }, // T_PLUS_PLUS
    { {         0}, {   0} },               
};

SR_ s_145[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR_ s_146[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       262}, { 150} }, // T_SEMICOLON
    { {         0}, {   0} },               
};

SR_ s_147[] =
{
    { { REQ_TOKEN}, {   2} },           
    { {       267}, { 151} }, // T_ENDIF
    { {         0}, {   0} },           
};

SR_ s_148[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       320}, { 152} }, // expression
    { {       286}, {  53} }, // T_NUM     
    { {       284}, {  54} }, // T_TRUE    
    { {       285}, {  55} }, // T_FALSE   
    { {       287}, {  56} }, // T_ID      
    { {       300}, {  57} }, // T_NOT     
    { {       282}, {  58} }, // T_OPEN    
    { {       321}, {  59} }, // list      
    { {       277}, {  60} }, // T_OPEN_SQ 
    { {         0}, {   0} },              
};

SR_ s_149[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR_ s_150[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR_ s_151[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR_ s_152[] =
{
    { { REQ_TOKEN}, {  14} },               
    { {       283}, { 153} }, // T_CLOSE    
    { {       294}, {  77} }, // T_ADD      
    { {       295}, {  78} }, // T_SUB      
    { {       296}, {  79} }, // T_MUL      
    { {       297}, {  80} }, // T_DIV      
    { {       298}, {  81} }, // T_MOD      
    { {       292}, {  82} }, // T_LESS     
    { {       293}, {  83} }, // T_GR       
    { {       291}, {  84} }, // T_EQ       
    { {       290}, {  85} }, // T_AND      
    { {       289}, {  86} }, // T_OR       
    { {       288}, {  87} }, // T_SHIFT    
    { {       299}, {  88} }, // T_PLUS_PLUS
    { {         0}, {   0} },               
};

SR_ s_153[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};


// State array:
SR_ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
ParserBase::ParserBase()
:
    d_token(Reserved_::UNDETERMINED_),
    // $insert baseclasscode
    d_requiredTokens_(0)
{
}

// base/clearin
void ParserBase::clearin_()
{
    d_nErrors_ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    // $insert LTYPEclear
    d_locationStack.clear();
    d_token = Reserved_::UNDETERMINED_;
    d_next = TokenPair{ Reserved_::UNDETERMINED_, STYPE_{} };
    d_recovery = false;
    d_acceptedTokens_ = d_requiredTokens_;
    d_val_ = STYPE_{};

    push_(0);
}

// base/debugfunctions

void ParserBase::setDebug(bool mode)
{
    d_actionCases_ = false;
    d_debug_ = mode;
}

void ParserBase::setDebug(DebugMode_ mode)
{
    d_actionCases_ = mode & ACTIONCASES;
    d_debug_ =       mode & ON;
}

// base/lex
void ParserBase::lex_(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved_::EOF_;

    d_terminalToken = true;
}

// base/lookup
int ParserBase::lookup_() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR_ const *sr = s_state[d_state];
    SR_ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN_;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void ParserBase::pop_(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

    // $insert LTYPEpop
    d_lsp = &d_locationStack[d_stackIdx];
}

// base/poptoken
void ParserBase::popToken_()
{
    d_token = d_next.first;
    d_val_ = d_token >= 0 ? std::move(d_next.second) : STYPE_{};

    d_next.first = Reserved_::UNDETERMINED_;
}

// base/push
void ParserBase::push_(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize_() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION_;
        d_stateStack.resize(newSize);
        // $insert LTYPEresize
        d_locationStack.resize(newSize);
    }

    ++d_stackIdx;
    // $insert LTYPEpush
    *(d_lsp = &d_locationStack[d_stackIdx]) = d_loc_;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val_) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void ParserBase::pushToken_(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val_) };
    d_token = token;
}

// base/redotoken
void ParserBase::redoToken_()
{
    if (d_token != Reserved_::UNDETERMINED_)
        pushToken_(d_token);
}

// base/reduce
void ParserBase::reduce_(int rule)
{
    PI_ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop_(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void ParserBase::shift_(int action)
{
    push_(action);
    popToken_();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens_ = 0;
    }
}

// base/startrecovery
void ParserBase::startRecovery_()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken_(Reserved_::errTok_);      // specify errTok_ as next token
    push_(lookup_());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t ParserBase::top_() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Parser::errorRecovery_()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens_ >= d_requiredTokens_)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors_;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top_()][0].d_type & ERR_ITEM))
    {
        pop_();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle_ for details.

    startRecovery_();
}

// derived/executeaction
void Parser::executeAction_(int production)
try
{
    if (token_() != Reserved_::UNDETERMINED_)
        pushToken_(token_());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 49 "while.y"
        {
         std::cout << "start -> T_PROGRAM T_ID(" << *vs_(-4).name << ") declarations T_BEGIN statements T_END" << std::endl;
         }
        break;

        case 2:
#line 56 "while.y"
        {
         std::cout << "type_sequence -> type" << std::endl;
         }
        break;

        case 3:
#line 61 "while.y"
        {
         std::cout << "type_sequence -> type" << std::endl;
         }
        break;

        case 4:
#line 68 "while.y"
        {
         std::cout << "declarations -> (epsilon)" << std::endl;
         }
        break;

        case 5:
#line 73 "while.y"
        {
         std::cout << "declarations -> declaration declarations" << std::endl;
         }
        break;

        case 6:
#line 80 "while.y"
        {
         std::cout << "declaration -> type variable_sequence T_SEMICOLON" << std::endl;
         }
        break;

        case 7:
#line 85 "while.y"
        {
         std::cout << "declaration -> type T_LIST T_ID T_SEMICOLON" << std::endl;
         }
        break;

        case 8:
#line 90 "while.y"
        {
         std::cout << "declaration -> T_LESS type_sequence T_GR T_ID T_SEMICOLON" << std::endl;
         }
        break;

        case 9:
#line 97 "while.y"
        {
         std::cout << "type -> T_INTEGER" << std::endl;
         }
        break;

        case 10:
#line 102 "while.y"
        {
         std::cout << "type -> T_BOOLEAN" << std::endl;
         }
        break;

        case 11:
#line 109 "while.y"
        {
         std::cout << "variable_sequence -> T_ID" << std::endl;
         }
        break;

        case 12:
#line 114 "while.y"
        {
         std::cout << "variable_sequence -> variable_sequence T_COMMA T_ID" << std::endl;
         }
        break;

        case 13:
#line 121 "while.y"
        {
         std::cout << "statements -> statement" << std::endl;
         }
        break;

        case 14:
#line 126 "while.y"
        {
         std::cout << "statements -> statement statements" << std::endl;
         }
        break;

        case 15:
#line 133 "while.y"
        {
         std::cout << "statement -> T_SKIP T_SEMICOLON" << std::endl;
         }
        break;

        case 16:
#line 138 "while.y"
        {
         std::cout << "statement -> assignment" << std::endl;
         }
        break;

        case 17:
#line 143 "while.y"
        {
         std::cout << "statement -> read" << std::endl;
         }
        break;

        case 18:
#line 148 "while.y"
        {
         std::cout << "statement -> write" << std::endl;
         }
        break;

        case 19:
#line 153 "while.y"
        {
         std::cout << "statement -> branch" << std::endl;
         }
        break;

        case 20:
#line 158 "while.y"
        {
         std::cout << "statement -> loop" << std::endl;
         }
        break;

        case 21:
#line 163 "while.y"
        {
         std::cout << "statement -> T_OPEN_SQ statement_no_semi T_PARALLEL statement_no_semi T_CLOSE T_SEMICOLON" << std::endl;
         }
        break;

        case 22:
#line 170 "while.y"
        {
         std::cout << "statement_no_semi -> assignment_no_semi" << std::endl;
         }
        break;

        case 23:
#line 175 "while.y"
        {
         std::cout << "statement_no_semi -> read_no_semi" << std::endl;
         }
        break;

        case 24:
#line 180 "while.y"
        {
         std::cout << "statement_no_semi -> read_no_semi" << std::endl;
         }
        break;

        case 25:
#line 187 "while.y"
        {
         std::cout << "list_sequence -> expression" << std::endl;
         }
        break;

        case 26:
#line 192 "while.y"
        {
         std::cout << "list_sequence -> list_sequence T_COMMA expression" << std::endl;
         }
        break;

        case 27:
#line 201 "while.y"
        {
         std::cout << "assignment -> T_ID(" << *vs_(-3).name << ") T_ASSIGN expression T_SEMICOLON" << std::endl;
         }
        break;

        case 28:
#line 206 "while.y"
        {
         std::cout << "assignment -> T_ID T_APPENDMENT expression T_SEMICOLON" << std::endl;
         }
        break;

        case 29:
#line 211 "while.y"
        {
         std::cout << "assignment -> T_ID T_OPEN_SQ T_NUM T_CLOSE_SQ T_ASSIGN expression T_SEMICOLON" << std::endl;
         }
        break;

        case 30:
#line 216 "while.y"
        {
         std::cout << "assignment -> T_ID T_DOT T_NUM T_ASSIGN expression T_SEMICOLON" << std::endl;
         }
        break;

        case 31:
#line 223 "while.y"
        {
         std::cout << "assignment_no_semi -> T_ID T_ASSIGN expression" << std::endl;
         }
        break;

        case 32:
#line 230 "while.y"
        {
         std::cout << "read -> T_READ T_OPEN T_ID(" << *vs_(-2).name << ") T_CLOSE T_SEMICOLON" << std::endl;
         }
        break;

        case 33:
#line 235 "while.y"
        {
         std::cout << "read -> T_READ T_OPEN T_ID T_DOT T_NUM T_CLOSE T_SEMICOLON" << std::endl;
         }
        break;

        case 34:
#line 241 "while.y"
        {
         std::cout << "read_no_semi -> T_READ T_OPEN T_ID T_CLOSE" << std::endl;
         }
        break;

        case 35:
#line 248 "while.y"
        {
         std::cout << "write -> T_WRITE T_OPEN expression T_CLOSE T_SEMICOLON" << std::endl;
         }
        break;

        case 36:
#line 255 "while.y"
        {
         std::cout << "write_no_semi -> T_WRITE T_OPEN expression T_CLOSE" << std::endl;
         }
        break;

        case 37:
#line 262 "while.y"
        {
         std::cout << "branch -> T_IF expression T_THEN statements T_ENDIF" << std::endl;
         }
        break;

        case 38:
#line 267 "while.y"
        {
         std::cout << "branch -> T_IF expression T_THEN statements T_ELSE statements T_ENDIF" << std::endl;
         }
        break;

        case 39:
#line 274 "while.y"
        {
         std::cout << "loop -> T_WHILE expression T_DO statements T_DONE" << std::endl;
         }
        break;

        case 40:
#line 281 "while.y"
        {
         std::cout << "list -> T_OPEN_SQ T_CLOSE_SQ" << std::endl;
         }
        break;

        case 41:
#line 286 "while.y"
        {
         std::cout << "list -> T_OPEN_SQ list_sequence T_CLOSE_SQ" << std::endl;
         }
        break;

        case 42:
#line 293 "while.y"
        {
         std::cout << "expression -> T_NUM(" << *vs_(0).value << ")" << std::endl;
         }
        break;

        case 43:
#line 298 "while.y"
        {
         std::cout << "expression -> T_TRUE" << std::endl;
         }
        break;

        case 44:
#line 303 "while.y"
        {
         std::cout << "expression -> T_FALSE" << std::endl;
         }
        break;

        case 45:
#line 308 "while.y"
        {
         std::cout << "expression -> T_ID(" << *vs_(0).name << ")" << std::endl;
         }
        break;

        case 46:
#line 313 "while.y"
        {
         std::cout << "expression -> expression T_ADD expression" << std::endl;
         }
        break;

        case 47:
#line 318 "while.y"
        {
         std::cout << "expression -> expression T_SUB expression" << std::endl;
         }
        break;

        case 48:
#line 323 "while.y"
        {
         std::cout << "expression -> expression T_MUL expression" << std::endl;
         }
        break;

        case 49:
#line 328 "while.y"
        {
         std::cout << "expression -> expression T_DIV expression" << std::endl;
         }
        break;

        case 50:
#line 333 "while.y"
        {
         std::cout << "expression -> expression T_MOD expression" << std::endl;
         }
        break;

        case 51:
#line 338 "while.y"
        {
         std::cout << "expression -> expression T_LESS expression" << std::endl;
         }
        break;

        case 52:
#line 343 "while.y"
        {
         std::cout << "expression -> expression T_GR expression" << std::endl;
         }
        break;

        case 53:
#line 348 "while.y"
        {
         std::cout << "expression -> expression T_EQ expression" << std::endl;
         }
        break;

        case 54:
#line 353 "while.y"
        {
         std::cout << "expression -> expression T_AND expression" << std::endl;
         }
        break;

        case 55:
#line 358 "while.y"
        {
         std::cout << "expression -> expression T_OR expression" << std::endl;
         }
        break;

        case 56:
#line 363 "while.y"
        {
         std::cout << "expression -> T_NOT expression" << std::endl;
         }
        break;

        case 57:
#line 368 "while.y"
        {
         std::cout << "expression -> T_OPEN expression T_CLOSE" << std::endl;
         }
        break;

        case 58:
#line 373 "while.y"
        {
         std::cout << "expression -> expression T_SHIFT expression" << std::endl;
         }
        break;

        case 59:
#line 378 "while.y"
        {
         std::cout << "expression -> T_OPEN expression T_QUESTION expression T_COLON expression T_CLOSE" << std::endl;
         }
        break;

        case 60:
#line 383 "while.y"
        {
         std::cout << "expression -> T_ID T_OPEN_SQ T_NUM T_CLOSE_SQ" << std::endl;
         }
        break;

        case 61:
#line 388 "while.y"
        {
         std::cout << "expression -> list" << std::endl;
         }
        break;

        case 62:
#line 393 "while.y"
        {
         std::cout << "expression -> expression T_PLUS_PLUS expression" << std::endl;
         }
        break;

        case 63:
#line 398 "while.y"
        {
         std::cout << "expression -> T_ID T_DOT T_NUM" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Parser::nextCycle_()
try
{
    if (s_state[state_()]->d_type & REQ_TOKEN)
        nextToken_();              // obtain next token


    int action = lookup_();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift_(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery_())
            redoToken_();
        else
            executeAction_(-action);
                                            // next token is the rule's LHS
        reduce_(-action); 
        return;
    }

    if (recovery_())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery_)
{
    if (not recovery_())
        errorRecovery_();
    else
    {
        if (token_() == Reserved_::EOF_)
            ABORT();
        popToken_();               // skip the failing token
    }
}


// derived/nexttoken
void Parser::nextToken_()
{ 
    // If d_token is Reserved_::UNDETERMINED_ then if savedToken_() is
    // Reserved_::UNDETERMINED_ another token is obtained from lex(). Then
    // savedToken_() is assigned to d_token.

                                    // no need for a token: got one already
    if (token_() != Reserved_::UNDETERMINED_) 
    {
        return;                             
    }

    if (savedToken_() != Reserved_::UNDETERMINED_)
    {
        popToken_();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens_;       // accept another token (see
                                    // errorRecover())
        lex_(lex());
        print_();
    }
    print();
}

// derived/print
void Parser::print_()
{
// $insert print
}

// derived/parse
int Parser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin_.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin_();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle_();
    }
}
catch (Return_ retValue)
{
    return retValue or d_nErrors_;
}


// derived/tail


