// Generated by Bisonc++ V6.08.00 on Sun, 02 Nov 2025 19:51:41 +0100

// base/comment

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved_::UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN_ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok_
// which is applied. In this errTok_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved_
    {
        UNDETERMINED_   = -2,
        EOF_            = -1,
        errTok_         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    inline bool operator&(StateType lhs, StateType rhs)
    {
        return (static_cast<int>(lhs) & rhs) != 0;
    }
    enum StateTransition
    {
        ACCEPT_   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI_     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR_     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION_ = 10
    };

// Productions Info Records:
PI_ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {292, 6}, // 1: program (T_PROGRAM) ->  T_PROGRAM T_ID declarations T_BEGIN statements T_END
     {293, 0}, // 2: declarations ->  <empty>
     {293, 2}, // 3: declarations ->  declaration declarations
     {295, 3}, // 4: declaration (T_INTEGER) ->  T_INTEGER T_ID T_SEMICOLON
     {295, 3}, // 5: declaration (T_BOOLEAN) ->  T_BOOLEAN T_ID T_SEMICOLON
     {294, 1}, // 6: statements ->  statement
     {294, 2}, // 7: statements ->  statement statements
     {296, 2}, // 8: statement (T_SKIP) ->  T_SKIP T_SEMICOLON
     {296, 1}, // 9: statement ->  assignment
     {296, 1}, // 10: statement ->  read
     {296, 1}, // 11: statement ->  write
     {296, 1}, // 12: statement ->  branch
     {296, 1}, // 13: statement ->  loop
     {297, 4}, // 14: assignment (T_ID) ->  T_ID T_ASSIGN expression T_SEMICOLON
     {298, 5}, // 15: read (T_READ) ->  T_READ T_OPEN T_ID T_CLOSE T_SEMICOLON
     {299, 5}, // 16: write (T_WRITE) ->  T_WRITE T_OPEN expression T_CLOSE T_SEMICOLON
     {300, 5}, // 17: branch (T_IF) ->  T_IF expression T_THEN statements T_ENDIF
     {300, 7}, // 18: branch (T_IF) ->  T_IF expression T_THEN statements T_ELSE statements T_ENDIF
     {301, 5}, // 19: loop (T_WHILE) ->  T_WHILE expression T_DO statements T_DONE
     {302, 1}, // 20: expression (T_NUM) ->  T_NUM
     {302, 1}, // 21: expression (T_TRUE) ->  T_TRUE
     {302, 1}, // 22: expression (T_FALSE) ->  T_FALSE
     {302, 1}, // 23: expression (T_ID) ->  T_ID
     {302, 3}, // 24: expression (T_ADD) ->  expression T_ADD expression
     {302, 3}, // 25: expression (T_SUB) ->  expression T_SUB expression
     {302, 3}, // 26: expression (T_MUL) ->  expression T_MUL expression
     {302, 3}, // 27: expression (T_DIV) ->  expression T_DIV expression
     {302, 3}, // 28: expression (T_MOD) ->  expression T_MOD expression
     {302, 3}, // 29: expression (T_LESS) ->  expression T_LESS expression
     {302, 3}, // 30: expression (T_GR) ->  expression T_GR expression
     {302, 3}, // 31: expression (T_EQ) ->  expression T_EQ expression
     {302, 3}, // 32: expression (T_AND) ->  expression T_AND expression
     {302, 3}, // 33: expression (T_OR) ->  expression T_OR expression
     {302, 2}, // 34: expression (T_NOT) ->  T_NOT expression
     {302, 3}, // 35: expression (T_OPEN) ->  T_OPEN expression T_CLOSE
     {302, 3}, // 36: expression (T_SHIFT) ->  expression T_SHIFT expression
     {303, 1}, // 37: program_$ ->  program
};

// State info and SR_ transitions for each state.


SR_ s_0[] =
{
    { { REQ_TOKEN}, { 3} },             
    { {       292}, { 1} }, // program  
    { {       257}, { 2} }, // T_PROGRAM
    { {         0}, { 0} },             
};

SR_ s_1[] =
{
    { { REQ_TOKEN}, {       2} }, 
    { {      EOF_}, { ACCEPT_} }, 
    { {         0}, {       0} }, 
};

SR_ s_2[] =
{
    { { REQ_TOKEN}, { 2} },        
    { {       279}, { 3} }, // T_ID
    { {         0}, { 0} },        
};

SR_ s_3[] =
{
    { { REQ_DEF}, {  5} },                
    { {     293}, {  4} }, // declarations
    { {     295}, {  5} }, // declaration 
    { {     260}, {  6} }, // T_INTEGER   
    { {     261}, {  7} }, // T_BOOLEAN   
    { {       0}, { -2} },                
};

SR_ s_4[] =
{
    { { REQ_TOKEN}, { 2} },           
    { {       258}, { 8} }, // T_BEGIN
    { {         0}, { 0} },           
};

SR_ s_5[] =
{
    { { REQ_DEF}, {  5} },                
    { {     293}, {  9} }, // declarations
    { {     295}, {  5} }, // declaration 
    { {     260}, {  6} }, // T_INTEGER   
    { {     261}, {  7} }, // T_BOOLEAN   
    { {       0}, { -2} },                
};

SR_ s_6[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       279}, { 10} }, // T_ID
    { {         0}, {  0} },        
};

SR_ s_7[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       279}, { 11} }, // T_ID
    { {         0}, {  0} },        
};

SR_ s_8[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       294}, { 12} }, // statements
    { {       296}, { 13} }, // statement 
    { {       263}, { 14} }, // T_SKIP    
    { {       297}, { 15} }, // assignment
    { {       298}, { 16} }, // read      
    { {       299}, { 17} }, // write     
    { {       300}, { 18} }, // branch    
    { {       301}, { 19} }, // loop      
    { {       279}, { 20} }, // T_ID      
    { {       271}, { 21} }, // T_READ    
    { {       272}, { 22} }, // T_WRITE   
    { {       264}, { 23} }, // T_IF      
    { {       268}, { 24} }, // T_WHILE   
    { {         0}, {  0} },              
};

SR_ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR_ s_10[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       262}, { 25} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR_ s_11[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       262}, { 26} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR_ s_12[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       259}, { 27} }, // T_END
    { {         0}, {  0} },         
};

SR_ s_13[] =
{
    { { REQ_DEF}, { 14} },              
    { {     294}, { 28} }, // statements
    { {     296}, { 13} }, // statement 
    { {     263}, { 14} }, // T_SKIP    
    { {     297}, { 15} }, // assignment
    { {     298}, { 16} }, // read      
    { {     299}, { 17} }, // write     
    { {     300}, { 18} }, // branch    
    { {     301}, { 19} }, // loop      
    { {     279}, { 20} }, // T_ID      
    { {     271}, { 21} }, // T_READ    
    { {     272}, { 22} }, // T_WRITE   
    { {     264}, { 23} }, // T_IF      
    { {     268}, { 24} }, // T_WHILE   
    { {       0}, { -6} },              
};

SR_ s_14[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       262}, { 29} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR_ s_15[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR_ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR_ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR_ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR_ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR_ s_20[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       273}, { 30} }, // T_ASSIGN
    { {         0}, {  0} },            
};

SR_ s_21[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       274}, { 31} }, // T_OPEN
    { {         0}, {  0} },          
};

SR_ s_22[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       274}, { 32} }, // T_OPEN
    { {         0}, {  0} },          
};

SR_ s_23[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 33} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_24[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 40} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_25[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR_ s_26[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR_ s_27[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR_ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR_ s_29[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR_ s_30[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 41} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_31[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       279}, { 42} }, // T_ID
    { {         0}, {  0} },        
};

SR_ s_32[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 43} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_33[] =
{
    { { REQ_TOKEN}, { 13} },           
    { {       265}, { 44} }, // T_THEN 
    { {       286}, { 45} }, // T_ADD  
    { {       287}, { 46} }, // T_SUB  
    { {       288}, { 47} }, // T_MUL  
    { {       289}, { 48} }, // T_DIV  
    { {       290}, { 49} }, // T_MOD  
    { {       284}, { 50} }, // T_LESS 
    { {       285}, { 51} }, // T_GR   
    { {       283}, { 52} }, // T_EQ   
    { {       282}, { 53} }, // T_AND  
    { {       281}, { 54} }, // T_OR   
    { {       280}, { 55} }, // T_SHIFT
    { {         0}, {  0} },           
};

SR_ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR_ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR_ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR_ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR_ s_38[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 56} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_39[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 57} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_40[] =
{
    { { REQ_TOKEN}, { 13} },           
    { {       269}, { 58} }, // T_DO   
    { {       286}, { 45} }, // T_ADD  
    { {       287}, { 46} }, // T_SUB  
    { {       288}, { 47} }, // T_MUL  
    { {       289}, { 48} }, // T_DIV  
    { {       290}, { 49} }, // T_MOD  
    { {       284}, { 50} }, // T_LESS 
    { {       285}, { 51} }, // T_GR   
    { {       283}, { 52} }, // T_EQ   
    { {       282}, { 53} }, // T_AND  
    { {       281}, { 54} }, // T_OR   
    { {       280}, { 55} }, // T_SHIFT
    { {         0}, {  0} },           
};

SR_ s_41[] =
{
    { { REQ_TOKEN}, { 13} },               
    { {       262}, { 59} }, // T_SEMICOLON
    { {       286}, { 45} }, // T_ADD      
    { {       287}, { 46} }, // T_SUB      
    { {       288}, { 47} }, // T_MUL      
    { {       289}, { 48} }, // T_DIV      
    { {       290}, { 49} }, // T_MOD      
    { {       284}, { 50} }, // T_LESS     
    { {       285}, { 51} }, // T_GR       
    { {       283}, { 52} }, // T_EQ       
    { {       282}, { 53} }, // T_AND      
    { {       281}, { 54} }, // T_OR       
    { {       280}, { 55} }, // T_SHIFT    
    { {         0}, {  0} },               
};

SR_ s_42[] =
{
    { { REQ_TOKEN}, {  2} },           
    { {       275}, { 60} }, // T_CLOSE
    { {         0}, {  0} },           
};

SR_ s_43[] =
{
    { { REQ_TOKEN}, { 13} },           
    { {       275}, { 61} }, // T_CLOSE
    { {       286}, { 45} }, // T_ADD  
    { {       287}, { 46} }, // T_SUB  
    { {       288}, { 47} }, // T_MUL  
    { {       289}, { 48} }, // T_DIV  
    { {       290}, { 49} }, // T_MOD  
    { {       284}, { 50} }, // T_LESS 
    { {       285}, { 51} }, // T_GR   
    { {       283}, { 52} }, // T_EQ   
    { {       282}, { 53} }, // T_AND  
    { {       281}, { 54} }, // T_OR   
    { {       280}, { 55} }, // T_SHIFT
    { {         0}, {  0} },           
};

SR_ s_44[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       294}, { 62} }, // statements
    { {       296}, { 13} }, // statement 
    { {       263}, { 14} }, // T_SKIP    
    { {       297}, { 15} }, // assignment
    { {       298}, { 16} }, // read      
    { {       299}, { 17} }, // write     
    { {       300}, { 18} }, // branch    
    { {       301}, { 19} }, // loop      
    { {       279}, { 20} }, // T_ID      
    { {       271}, { 21} }, // T_READ    
    { {       272}, { 22} }, // T_WRITE   
    { {       264}, { 23} }, // T_IF      
    { {       268}, { 24} }, // T_WHILE   
    { {         0}, {  0} },              
};

SR_ s_45[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 63} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_46[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 64} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_47[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 65} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_48[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 66} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_49[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 67} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_50[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 68} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_51[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 69} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_52[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 70} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_53[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 71} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_54[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 72} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_55[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       302}, { 73} }, // expression
    { {       278}, { 34} }, // T_NUM     
    { {       276}, { 35} }, // T_TRUE    
    { {       277}, { 36} }, // T_FALSE   
    { {       279}, { 37} }, // T_ID      
    { {       291}, { 38} }, // T_NOT     
    { {       274}, { 39} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR_ s_56[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -34} }, 
};

SR_ s_57[] =
{
    { { REQ_TOKEN}, { 13} },           
    { {       275}, { 74} }, // T_CLOSE
    { {       286}, { 45} }, // T_ADD  
    { {       287}, { 46} }, // T_SUB  
    { {       288}, { 47} }, // T_MUL  
    { {       289}, { 48} }, // T_DIV  
    { {       290}, { 49} }, // T_MOD  
    { {       284}, { 50} }, // T_LESS 
    { {       285}, { 51} }, // T_GR   
    { {       283}, { 52} }, // T_EQ   
    { {       282}, { 53} }, // T_AND  
    { {       281}, { 54} }, // T_OR   
    { {       280}, { 55} }, // T_SHIFT
    { {         0}, {  0} },           
};

SR_ s_58[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       294}, { 75} }, // statements
    { {       296}, { 13} }, // statement 
    { {       263}, { 14} }, // T_SKIP    
    { {       297}, { 15} }, // assignment
    { {       298}, { 16} }, // read      
    { {       299}, { 17} }, // write     
    { {       300}, { 18} }, // branch    
    { {       301}, { 19} }, // loop      
    { {       279}, { 20} }, // T_ID      
    { {       271}, { 21} }, // T_READ    
    { {       272}, { 22} }, // T_WRITE   
    { {       264}, { 23} }, // T_IF      
    { {       268}, { 24} }, // T_WHILE   
    { {         0}, {  0} },              
};

SR_ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR_ s_60[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       262}, { 76} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR_ s_61[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       262}, { 77} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR_ s_62[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       267}, { 78} }, // T_ENDIF
    { {       266}, { 79} }, // T_ELSE 
    { {         0}, {  0} },           
};

SR_ s_63[] =
{
    { { REQ_DEF}, {   4} },         
    { {     288}, {  47} }, // T_MUL
    { {     289}, {  48} }, // T_DIV
    { {     290}, {  49} }, // T_MOD
    { {       0}, { -24} },         
};

SR_ s_64[] =
{
    { { REQ_DEF}, {   4} },         
    { {     288}, {  47} }, // T_MUL
    { {     289}, {  48} }, // T_DIV
    { {     290}, {  49} }, // T_MOD
    { {       0}, { -25} },         
};

SR_ s_65[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -26} }, 
};

SR_ s_66[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -27} }, 
};

SR_ s_67[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -28} }, 
};

SR_ s_68[] =
{
    { { REQ_DEF}, {   6} },         
    { {     286}, {  45} }, // T_ADD
    { {     287}, {  46} }, // T_SUB
    { {     288}, {  47} }, // T_MUL
    { {     289}, {  48} }, // T_DIV
    { {     290}, {  49} }, // T_MOD
    { {       0}, { -29} },         
};

SR_ s_69[] =
{
    { { REQ_DEF}, {   6} },         
    { {     286}, {  45} }, // T_ADD
    { {     287}, {  46} }, // T_SUB
    { {     288}, {  47} }, // T_MUL
    { {     289}, {  48} }, // T_DIV
    { {     290}, {  49} }, // T_MOD
    { {       0}, { -30} },         
};

SR_ s_70[] =
{
    { { REQ_DEF}, {   8} },          
    { {     286}, {  45} }, // T_ADD 
    { {     287}, {  46} }, // T_SUB 
    { {     288}, {  47} }, // T_MUL 
    { {     289}, {  48} }, // T_DIV 
    { {     290}, {  49} }, // T_MOD 
    { {     284}, {  50} }, // T_LESS
    { {     285}, {  51} }, // T_GR  
    { {       0}, { -31} },          
};

SR_ s_71[] =
{
    { { REQ_DEF}, {   9} },          
    { {     286}, {  45} }, // T_ADD 
    { {     287}, {  46} }, // T_SUB 
    { {     288}, {  47} }, // T_MUL 
    { {     289}, {  48} }, // T_DIV 
    { {     290}, {  49} }, // T_MOD 
    { {     284}, {  50} }, // T_LESS
    { {     285}, {  51} }, // T_GR  
    { {     283}, {  52} }, // T_EQ  
    { {       0}, { -32} },          
};

SR_ s_72[] =
{
    { { REQ_DEF}, {   9} },          
    { {     286}, {  45} }, // T_ADD 
    { {     287}, {  46} }, // T_SUB 
    { {     288}, {  47} }, // T_MUL 
    { {     289}, {  48} }, // T_DIV 
    { {     290}, {  49} }, // T_MOD 
    { {     284}, {  50} }, // T_LESS
    { {     285}, {  51} }, // T_GR  
    { {     283}, {  52} }, // T_EQ  
    { {       0}, { -33} },          
};

SR_ s_73[] =
{
    { { REQ_DEF}, {  11} },          
    { {     286}, {  45} }, // T_ADD 
    { {     287}, {  46} }, // T_SUB 
    { {     288}, {  47} }, // T_MUL 
    { {     289}, {  48} }, // T_DIV 
    { {     290}, {  49} }, // T_MOD 
    { {     284}, {  50} }, // T_LESS
    { {     285}, {  51} }, // T_GR  
    { {     283}, {  52} }, // T_EQ  
    { {     282}, {  53} }, // T_AND 
    { {     281}, {  54} }, // T_OR  
    { {       0}, { -36} },          
};

SR_ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR_ s_75[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       270}, { 80} }, // T_DONE
    { {         0}, {  0} },          
};

SR_ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR_ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR_ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR_ s_79[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       294}, { 81} }, // statements
    { {       296}, { 13} }, // statement 
    { {       263}, { 14} }, // T_SKIP    
    { {       297}, { 15} }, // assignment
    { {       298}, { 16} }, // read      
    { {       299}, { 17} }, // write     
    { {       300}, { 18} }, // branch    
    { {       301}, { 19} }, // loop      
    { {       279}, { 20} }, // T_ID      
    { {       271}, { 21} }, // T_READ    
    { {       272}, { 22} }, // T_WRITE   
    { {       264}, { 23} }, // T_IF      
    { {       268}, { 24} }, // T_WHILE   
    { {         0}, {  0} },              
};

SR_ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR_ s_81[] =
{
    { { REQ_TOKEN}, {  2} },           
    { {       267}, { 82} }, // T_ENDIF
    { {         0}, {  0} },           
};

SR_ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};


// State array:
SR_ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
ParserBase::ParserBase()
:
    d_token(Reserved_::UNDETERMINED_),
    // $insert baseclasscode
    d_requiredTokens_(0)
{
}

// base/clearin
void ParserBase::clearin_()
{
    d_nErrors_ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    // $insert LTYPEclear
    d_locationStack.clear();
    d_token = Reserved_::UNDETERMINED_;
    d_next = TokenPair{ Reserved_::UNDETERMINED_, STYPE_{} };
    d_recovery = false;
    d_acceptedTokens_ = d_requiredTokens_;
    d_val_ = STYPE_{};

    push_(0);
}

// base/debugfunctions

void ParserBase::setDebug(bool mode)
{
    d_actionCases_ = false;
    d_debug_ = mode;
}

void ParserBase::setDebug(DebugMode_ mode)
{
    d_actionCases_ = mode & ACTIONCASES;
    d_debug_ =       mode & ON;
}

// base/lex
void ParserBase::lex_(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved_::EOF_;

    d_terminalToken = true;
}

// base/lookup
int ParserBase::lookup_() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR_ const *sr = s_state[d_state];
    SR_ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN_;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void ParserBase::pop_(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

    // $insert LTYPEpop
    d_lsp = &d_locationStack[d_stackIdx];
}

// base/poptoken
void ParserBase::popToken_()
{
    d_token = d_next.first;
    d_val_ = d_token >= 0 ? std::move(d_next.second) : STYPE_{};

    d_next.first = Reserved_::UNDETERMINED_;
}

// base/push
void ParserBase::push_(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize_() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION_;
        d_stateStack.resize(newSize);
        // $insert LTYPEresize
        d_locationStack.resize(newSize);
    }

    ++d_stackIdx;
    // $insert LTYPEpush
    *(d_lsp = &d_locationStack[d_stackIdx]) = d_loc_;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val_) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void ParserBase::pushToken_(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val_) };
    d_token = token;
}

// base/redotoken
void ParserBase::redoToken_()
{
    if (d_token != Reserved_::UNDETERMINED_)
        pushToken_(d_token);
}

// base/reduce
void ParserBase::reduce_(int rule)
{
    PI_ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop_(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void ParserBase::shift_(int action)
{
    push_(action);
    popToken_();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens_ = 0;
    }
}

// base/startrecovery
void ParserBase::startRecovery_()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken_(Reserved_::errTok_);      // specify errTok_ as next token
    push_(lookup_());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t ParserBase::top_() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Parser::errorRecovery_()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens_ >= d_requiredTokens_)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors_;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top_()][0].d_type & ERR_ITEM))
    {
        pop_();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle_ for details.

    startRecovery_();
}

// derived/executeaction
void Parser::executeAction_(int production)
try
{
    if (token_() != Reserved_::UNDETERMINED_)
        pushToken_(token_());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 43 "while.y"
        {
         std::cout << "start -> T_PROGRAM T_ID(" << *vs_(-4).name << ") declarations T_BEGIN statements T_END" << std::endl;
         }
        break;

        case 2:
#line 50 "while.y"
        {
         std::cout << "declarations -> (epsilon)" << std::endl;
         }
        break;

        case 3:
#line 55 "while.y"
        {
         std::cout << "declarations -> declaration declarations" << std::endl;
         }
        break;

        case 4:
#line 62 "while.y"
        {
         std::cout << "declaration -> T_INTEGER T_ID(" << *vs_(-1).name << ") T_SEMICOLON" << std::endl;
         }
        break;

        case 5:
#line 67 "while.y"
        {
         std::cout << "declaration -> T_BOOLEAN T_ID(" << *vs_(-1).name << ") T_SEMICOLON" << std::endl;
         }
        break;

        case 6:
#line 74 "while.y"
        {
         std::cout << "statements -> statement" << std::endl;
         }
        break;

        case 7:
#line 79 "while.y"
        {
         std::cout << "statements -> statement statements" << std::endl;
         }
        break;

        case 8:
#line 86 "while.y"
        {
         std::cout << "statement -> T_SKIP T_SEMICOLON" << std::endl;
         }
        break;

        case 9:
#line 91 "while.y"
        {
         std::cout << "statement -> assignment" << std::endl;
         }
        break;

        case 10:
#line 96 "while.y"
        {
         std::cout << "statement -> read" << std::endl;
         }
        break;

        case 11:
#line 101 "while.y"
        {
         std::cout << "statement -> write" << std::endl;
         }
        break;

        case 12:
#line 106 "while.y"
        {
         std::cout << "statement -> branch" << std::endl;
         }
        break;

        case 13:
#line 111 "while.y"
        {
         std::cout << "statement -> loop" << std::endl;
         }
        break;

        case 14:
#line 118 "while.y"
        {
         std::cout << "assignment -> T_ID(" << *vs_(-3).name << ") T_ASSIGN expression T_SEMICOLON" << std::endl;
         }
        break;

        case 15:
#line 125 "while.y"
        {
         std::cout << "read -> T_READ T_OPEN T_ID(" << *vs_(-2).name << ") T_CLOSE T_SEMICOLON" << std::endl;
         }
        break;

        case 16:
#line 132 "while.y"
        {
         std::cout << "write -> T_WRITE T_OPEN expression T_CLOSE T_SEMICOLON" << std::endl;
         }
        break;

        case 17:
#line 139 "while.y"
        {
         std::cout << "branch -> T_IF expression T_THEN statements T_ENDIF" << std::endl;
         }
        break;

        case 18:
#line 144 "while.y"
        {
         std::cout << "branch -> T_IF expression T_THEN statements T_ELSE statements T_ENDIF" << std::endl;
         }
        break;

        case 19:
#line 151 "while.y"
        {
         std::cout << "loop -> T_WHILE expression T_DO statements T_DONE" << std::endl;
         }
        break;

        case 20:
#line 158 "while.y"
        {
         std::cout << "expression -> T_NUM(" << *vs_(0).value << ")" << std::endl;
         }
        break;

        case 21:
#line 163 "while.y"
        {
         std::cout << "expression -> T_TRUE" << std::endl;
         }
        break;

        case 22:
#line 168 "while.y"
        {
         std::cout << "expression -> T_FALSE" << std::endl;
         }
        break;

        case 23:
#line 173 "while.y"
        {
         std::cout << "expression -> T_ID(" << *vs_(0).name << ")" << std::endl;
         }
        break;

        case 24:
#line 178 "while.y"
        {
         std::cout << "expression -> expression T_ADD expression" << std::endl;
         }
        break;

        case 25:
#line 183 "while.y"
        {
         std::cout << "expression -> expression T_SUB expression" << std::endl;
         }
        break;

        case 26:
#line 188 "while.y"
        {
         std::cout << "expression -> expression T_MUL expression" << std::endl;
         }
        break;

        case 27:
#line 193 "while.y"
        {
         std::cout << "expression -> expression T_DIV expression" << std::endl;
         }
        break;

        case 28:
#line 198 "while.y"
        {
         std::cout << "expression -> expression T_MOD expression" << std::endl;
         }
        break;

        case 29:
#line 203 "while.y"
        {
         std::cout << "expression -> expression T_LESS expression" << std::endl;
         }
        break;

        case 30:
#line 208 "while.y"
        {
         std::cout << "expression -> expression T_GR expression" << std::endl;
         }
        break;

        case 31:
#line 213 "while.y"
        {
         std::cout << "expression -> expression T_EQ expression" << std::endl;
         }
        break;

        case 32:
#line 218 "while.y"
        {
         std::cout << "expression -> expression T_AND expression" << std::endl;
         }
        break;

        case 33:
#line 223 "while.y"
        {
         std::cout << "expression -> expression T_OR expression" << std::endl;
         }
        break;

        case 34:
#line 228 "while.y"
        {
         std::cout << "expression -> T_NOT expression" << std::endl;
         }
        break;

        case 35:
#line 233 "while.y"
        {
         std::cout << "expression -> T_OPEN expression T_CLOSE" << std::endl;
         }
        break;

        case 36:
#line 238 "while.y"
        {
         std::cout << "expression -> expression T_SHIFT expression" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Parser::nextCycle_()
try
{
    if (s_state[state_()]->d_type & REQ_TOKEN)
        nextToken_();              // obtain next token


    int action = lookup_();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift_(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery_())
            redoToken_();
        else
            executeAction_(-action);
                                            // next token is the rule's LHS
        reduce_(-action); 
        return;
    }

    if (recovery_())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery_)
{
    if (not recovery_())
        errorRecovery_();
    else
    {
        if (token_() == Reserved_::EOF_)
            ABORT();
        popToken_();               // skip the failing token
    }
}


// derived/nexttoken
void Parser::nextToken_()
{ 
    // If d_token is Reserved_::UNDETERMINED_ then if savedToken_() is
    // Reserved_::UNDETERMINED_ another token is obtained from lex(). Then
    // savedToken_() is assigned to d_token.

                                    // no need for a token: got one already
    if (token_() != Reserved_::UNDETERMINED_) 
    {
        return;                             
    }

    if (savedToken_() != Reserved_::UNDETERMINED_)
    {
        popToken_();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens_;       // accept another token (see
                                    // errorRecover())
        lex_(lex());
        print_();
    }
    print();
}

// derived/print
void Parser::print_()
{
// $insert print
}

// derived/parse
int Parser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin_.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin_();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle_();
    }
}
catch (Return_ retValue)
{
    return retValue or d_nErrors_;
}


// derived/tail


